info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: DEBUG
    org.springframework: WARN
  profile: DEV

liquibase:
  user: actionsvc
  password: actionsvc
  default-schema: action
  url: jdbc:postgresql://localhost:6432/postgres
  changeLog: classpath:/database/changelog-master.yml

security:
  basic:
    enabled: false
    realm: sdc
  user:
    name: admin
    password: secret

management:
  security:
    roles: SUPERUSER
    enabled: true
  health:
    rabbit:
      enabled: false

server:
  port: 8151
  servlet-path: /

endpoints:
  info:
    enabled: true
    sensitive: false
  enabled: true

spring:
  output:
    ansi:
      enabled: never
  application:
    name: ONS ActionService
    
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: actionsvc
    password: actionsvc
    driverClassName: org.postgresql.Driver
    tomcat:
      initial-size: 5
      max-active: 10
      max-idle: 5
      min-idle: 3

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        default_schema: action

 # all about redis
data-grid:
  # where is redis
  address: localhost:7379
  # when we create a list of actions being distib, how long should the list remain in redis after app death
  list-time-to-live-seconds: 10
  # when we try and create a list of ids being distrib how long should we wait to get the lock
  list-time-to-wait-seconds: 10
  #  after app death how long should the lock on all lists remain
  lock-time-to-live-seconds: 10
  report-lock-time-to-live-seconds: 300

# the thread that sends actions to handlers
action-distribution:
  # how many actions should we read each time we wake
  retrieval-max: 200
  # when we fail to send to rabbit how long should we pause for before retry
  retry-sleep-seconds: 30
  # how long to pause after each distribution exercise 
  delay-milli-seconds: 1000

 # the thread that executes plans to create the  actions
plan-execution:
  # pause after each execution exercise 
  delay-milli-seconds: 1000

 # calling the case svc endpoints
case-svc:
  case-group-path: /casegroups/{caseGroupId}
  case-by-case-get-path: /cases/{caseid}
  case-events-by-case-get-path: /cases/{caseid}/events
  case-events-by-case-post-path: /cases/{caseid}/events
  address-by-uprn-get-path: /addresses/{uprn}
  case-type-by-id-path: /casetypes/{casetypeid}
  connection-config:
    scheme: http
    host: localhost
    port: 8171
    username: admin
    password: secret
    # how many times should we attempt connection on failure
    retry-attempts: 10
    # sleep between retries
    retry-pause-milli-seconds: 5000
    # time to estab connection
    connect-timeout-milli-seconds: 5000
    # time to read response
    read-timeout-milli-seconds: 5000

 # calling the collectionexercise svc endpoints
collection-exercise-svc:
  collection-by-collection-exercise-get-path: /collectionexercises/{id}
  connection-config:
    scheme: http
    host: localhost
    port: 8145
    username: admin
    password: secret
    retry-attempts: 10
    retry-pause-milli-seconds: 5000
    connect-timeout-milli-seconds: 5000
    read-timeout-milli-seconds: 5000

 # calling the party svc endpoint
party-svc:
  party-by-sample-unit-type-and-id-path: /party-api/v1/parties/type/{sampleUnitType}/id/{partyId}
  connection-config:
    scheme: http
    host: localhost
    port: 5062
    username: dummy_user
    password: dummy_password
    retry-attempts: 1
    retry-pause-milli-seconds: 5000
    connect-timeout-milli-seconds: 5000
    read-timeout-milli-seconds: 5000

 # calling the survey svc endpoints
survey-svc:
  request-survey-path: /surveys/{surveyId}
  connection-config:
    scheme: http
    host: localhost
    port: 8080
    username: admin
    password: secret
    retry-attempts: 5
    retry-pause-milli-seconds: 5000
    connect-timeout-milli-seconds: 5000
    read-timeout-milli-seconds: 5000

 # looking for the ingest file
csv-ingest:
  directory: /tmp/csv
  file-pattern: '*.csv'
  #the poll-milliseconds property is not used at the moment due to a bug in spring context loading in integration tests
  poll-milliseconds: 10000

 # queue related
redelivery-policy:
  maxRedeliveries: -1
  initialRedeliveryDelay: 1000
  redeliveryDelay: 1000

 # queue service related
rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 6672
  virtualhost: /
  # When using publisher confirms, the cache size needs to be large enough otherwise channels can be closed before confirms are received.
  channelCacheSize: 100
  
messaging:
  backoffInitial: 5000
  backoffMultiplier: 3
  backoffMax: 45000
  consumingThreads: 1
  maxAttempts: 3
  prefetchCount: 10
  txSize: 1

report-settings:
  cron-expression: "0 * * * * *"

swagger-settings:
  swagger-ui-active: true
  group-name: actionservice-api
  title: Action Service API
  description: API for ${project.artifactId}
  version: ${project.version}

retries:
  maxAttempts: 3
  backoff: 5000